/**
 * Lightweight guardrails for the public /api/explain endpoint.
 * In-memory, per server instance: enough to stop casual abuse of a hackathon demo,
 * not a substitute for a real gateway. Pure module so it is unit-testable.
 */

export const LIMITS = {
  maxBodyBytes: 2_048,
  maxEdgeIds: 12,
  perIpPerMinute: 6,
  perIpPerHour: 40,
  globalPerHour: 300,
  cacheTtlMs: 60 * 60 * 1000,
  cacheMaxEntries: 200,
} as const;

/** Edge ids are generated by our build: "edge:<key>" or "edge:ai:<node>|<predicate>|<node>". */
export const EDGE_ID_RE = /^edge:[a-z0-9:_|-]{1,120}$/i;

type Hit = number[];
const ipHits = new Map<string, Hit>();
let globalHits: Hit = [];

function prune(hits: Hit, now: number, windowMs: number): Hit {
  return hits.filter((t) => now - t < windowMs);
}

export type RateDecision = { ok: true } | { ok: false; retryAfterSec: number; scope: "ip-minute" | "ip-hour" | "global" };

/** Sliding-window limiter. Call only for requests that will actually hit OpenAI (cache misses). */
export function checkRate(ip: string, now = Date.now()): RateDecision {
  const hits = prune(ipHits.get(ip) ?? [], now, 3_600_000);
  globalHits = prune(globalHits, now, 3_600_000);
  const lastMinute = hits.filter((t) => now - t < 60_000);
  if (lastMinute.length >= LIMITS.perIpPerMinute) return { ok: false, retryAfterSec: Math.ceil((60_000 - (now - lastMinute[0])) / 1000), scope: "ip-minute" };
  if (hits.length >= LIMITS.perIpPerHour) return { ok: false, retryAfterSec: Math.ceil((3_600_000 - (now - hits[0])) / 1000), scope: "ip-hour" };
  if (globalHits.length >= LIMITS.globalPerHour) return { ok: false, retryAfterSec: Math.ceil((3_600_000 - (now - globalHits[0])) / 1000), scope: "global" };
  hits.push(now);
  globalHits.push(now);
  ipHits.set(ip, hits);
  if (ipHits.size > 5_000) ipHits.clear(); // memory safety valve
  return { ok: true };
}

export function resetRateLimits() {
  ipHits.clear();
  globalHits = [];
}

/** Small TTL cache: identical explanation requests are served without a new OpenAI call. */
const cache = new Map<string, { at: number; value: unknown }>();

export const cacheKey = (edgeIds: string[], audience: string) => `${audience}|${[...new Set(edgeIds)].sort().join(",")}`;

export function cacheGet<T>(key: string, now = Date.now()): T | undefined {
  const hit = cache.get(key);
  if (!hit) return undefined;
  if (now - hit.at > LIMITS.cacheTtlMs) {
    cache.delete(key);
    return undefined;
  }
  return hit.value as T;
}

export function cacheSet(key: string, value: unknown, now = Date.now()) {
  if (cache.size >= LIMITS.cacheMaxEntries) cache.delete(cache.keys().next().value!);
  cache.set(key, { at: now, value });
}

export function clientIp(req: Request): string {
  const fwd = req.headers.get("x-forwarded-for");
  return (fwd?.split(",")[0] ?? req.headers.get("x-real-ip") ?? "unknown").trim();
}

/** Map any OpenAI/SDK failure to a calm, user-facing message. Never leaks provider details. */
export function friendlyAiError(err: unknown): { status: number; error: string; code: string } {
  const e = err as { status?: number; name?: string; code?: string; message?: string };
  if (e?.name === "APIConnectionTimeoutError" || /timed? ?out|timeout/i.test(e?.message ?? "")) {
    return { status: 504, code: "timeout", error: "The explanation took too long. The evidence below is unchanged. Please try again." };
  }
  if (e?.status === 429) return { status: 503, code: "busy", error: "The explanation service is busy right now. The evidence below is unchanged. Please try again in a minute." };
  if (/parsable|parse|schema/i.test(e?.message ?? "")) {
    return { status: 502, code: "invalid_output", error: "We could not produce a reliable explanation this time, so none is shown. The evidence below is unchanged. Please try again." };
  }
  return { status: 502, code: "unavailable", error: "The explanation service is unavailable right now. The evidence below is unchanged. Please try again." };
}
