import type { EvidenceStatus } from "@/lib/schemas";

/**
 * The ONLY place evidence-status styling is defined. Each status has a distinct
 * icon, label, color AND border style so it reads without color vision.
 */
export const STATUS_META: Record<EvidenceStatus, { label: string; icon: string; help: string; badge: string; card: string }> = {
  supported: {
    label: "Known / directly supported",
    icon: "●",
    help: "A cited source states this directly.",
    badge: "bg-supported-bg text-supported border border-solid border-supported",
    card: "border-l-4 border-solid border-l-supported",
  },
  inferred: {
    label: "AI-inferred",
    icon: "◇",
    help: "A hypothesis generated by AI or by combining evidence. Not established.",
    badge: "bg-inferred-bg text-inferred border border-dashed border-inferred",
    card: "border-l-4 border-dashed border-l-inferred",
  },
  contradictory: {
    label: "Contradictory",
    icon: "▲",
    help: "Sources disagree. Read both sides before relying on it.",
    badge: "bg-contradictory-bg text-contradictory border border-double border-contradictory",
    card: "border-l-4 border-double border-l-contradictory",
  },
  unknown: {
    label: "Unknown / insufficient evidence",
    icon: "?",
    help: "Not enough evidence to say either way.",
    badge: "bg-unknown-bg text-unknown border border-dotted border-unknown",
    card: "border-l-4 border-dotted border-l-unknown",
  },
};

export function StatusBadge({ status, compact = false }: { status: EvidenceStatus; compact?: boolean }) {
  const m = STATUS_META[status];
  return (
    <span title={m.help} className={`inline-flex items-center gap-1 whitespace-nowrap rounded px-2 py-0.5 text-xs font-medium ${m.badge}`}>
      <span aria-hidden>{m.icon}</span>
      {compact ? m.label.split(" /")[0] : m.label}
    </span>
  );
}

export function StatusLegend() {
  return (
    <div className="flex flex-wrap items-center gap-2 text-left">
      <span className="text-xs font-medium uppercase tracking-wide text-muted">Evidence status</span>
      {(Object.keys(STATUS_META) as EvidenceStatus[]).map((s) => (
        <StatusBadge key={s} status={s} />
      ))}
    </div>
  );
}

export function FixtureChip() {
  return (
    <span title="Hand-entered demo data. Not retrieved from the source yet." className="rounded bg-yellow-100 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-yellow-900">
      Demo fixture
    </span>
  );
}
